# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transformWindow(object):
    def setupUi(self, transformWindow):
        transformWindow.setObjectName("transformWindow")
        transformWindow.resize(644, 635)
        self.centralwidget = QtWidgets.QWidget(transformWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 621, 261))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 21))
        self.label.setObjectName("label")
        self.sourcepath = QtWidgets.QLineEdit(self.groupBox)
        self.sourcepath.setGeometry(QtCore.QRect(180, 30, 381, 21))
        self.sourcepath.setObjectName("sourcepath")
        self.sourcebrowseButton = QtWidgets.QToolButton(self.groupBox)
        self.sourcebrowseButton.setGeometry(QtCore.QRect(570, 30, 31, 22))
        self.sourcebrowseButton.setObjectName("sourcebrowseButton")
        self.listword = QtWidgets.QListWidget(self.groupBox)
        self.listword.setGeometry(QtCore.QRect(20, 60, 581, 192))
        self.listword.setObjectName("listword")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 621, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 151, 21))
        self.label_2.setObjectName("label_2")
        self.targetpath = QtWidgets.QLineEdit(self.groupBox_2)
        self.targetpath.setGeometry(QtCore.QRect(170, 30, 391, 21))
        self.targetpath.setObjectName("targetpath")
        self.targetbrowseButton = QtWidgets.QToolButton(self.groupBox_2)
        self.targetbrowseButton.setGeometry(QtCore.QRect(570, 30, 31, 22))
        self.targetbrowseButton.setObjectName("targetbrowseButton")
        self.listpdf = QtWidgets.QListWidget(self.groupBox_2)
        self.listpdf.setGeometry(QtCore.QRect(20, 60, 581, 192))
        self.listpdf.setObjectName("listpdf")
        self.showLoading = QtWidgets.QLabel(self.centralwidget)
        self.showLoading.setGeometry(QtCore.QRect(9, 289, 431, 16))
        self.showLoading.setObjectName("showLoading")
        self.multipeExecute = QtWidgets.QPushButton(self.centralwidget)
        self.multipeExecute.setGeometry(QtCore.QRect(440, 280, 81, 31))
        self.multipeExecute.setObjectName("multipeExecute")
        self.singleExecute = QtWidgets.QPushButton(self.centralwidget)
        self.singleExecute.setGeometry(QtCore.QRect(520, 280, 111, 31))
        self.singleExecute.setObjectName("singleExecute")
        transformWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(transformWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 24))
        self.menubar.setObjectName("menubar")
        transformWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(transformWindow)
        self.statusbar.setObjectName("statusbar")
        transformWindow.setStatusBar(self.statusbar)

        self.retranslateUi(transformWindow)
        QtCore.QMetaObject.connectSlotsByName(transformWindow)

    def retranslateUi(self, transformWindow):
        _translate = QtCore.QCoreApplication.translate
        transformWindow.setWindowTitle(_translate("transformWindow", "transformWindow"))
        self.groupBox.setTitle(_translate("transformWindow", "源"))
        self.label.setText(_translate("transformWindow", "请选择Word文档所在目录："))
        self.sourcebrowseButton.setText(_translate("transformWindow", "..."))
        self.groupBox_2.setTitle(_translate("transformWindow", "结果"))
        self.label_2.setText(_translate("transformWindow", "转换后PDF文件保存目录："))
        self.targetbrowseButton.setText(_translate("transformWindow", "..."))
        self.showLoading.setText(_translate("transformWindow", "转换进度"))
        self.multipeExecute.setText(_translate("transformWindow", "批量转换"))
        self.singleExecute.setText(_translate("transformWindow", "合并为一个PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transformWindow = QtWidgets.QMainWindow()
    ui = Ui_transformWindow()
    ui.setupUi(transformWindow)
    transformWindow.show()
    sys.exit(app.exec_())
